urls.py
from django.conf.urls import include
from django.urls import re_path as url
from django.contrib.auth.decorators import login_required
from django.contrib.auth import views as auth_views
from . import views

app_name = "accounts"

urlpatterns = [
    url(r'^login/$', views.login, name='login'),
    url(r'^auth/', views.auth_view),
    url(r'^registration/', views.registration, name='account_signup'),
    url(r'^profile/$', login_required(views.profile), name='profile'),
    url(r'^profile/change/$', login_required(views.profile_change),
        name='profile-update'),
    url(r'^change_password/$', login_required(views.change_password),
        name='change_password'),
    url(r'^password_reset/$', views.PasswordResetView.as_view(),
        name='password_reset'),
    url(r'^password_reset/done/$', views.reset_done,
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z]+)/(?P<token>.+)/$',
        auth_views.PasswordResetConfirmView.as_view(),
        name='password_reset_confirm'),
    url(r'^password_reset/complete/$', views.reset_complete,
        name='password_reset_complete'),

    url("^soc/", include("social_django.urls", namespace="social")),
]

templates/accounts/login.html
{% extends "generic_views/base.html" %}
{%load static %}
{% block body %}
	<body class="login-layout light-login">
		<div class="main-container">
			<div class="main-content">
				<div class="row">
					<div class="col-sm-10 col-sm-offset-1">
						<div class="login-container">
							<div class="center">
								{%include "accounts/login_logo.html" %}
							</div>
							<div class="space-6"></div>
							<div class="position-relative">
								<div id="login-box" class="login-box visible widget-box no-border">
									<div class="widget-body">
										<div class="widget-main">
											<h4 class="header blue lighter bigger">
											<i class="ace-icon fa fa-coffee green"></i>
											Ingreso
											</h4>
											{% if invalid %}
												{% if not verbose_error %}
													<h4 class="header red">
													<i class="ace-icon fa fa-warning yellow"></i>
													Usuario o contraseña inválidas
													</h4>
												{% else %}
													<h4 class="header red">
													<i class="ace-icon fa fa-warning yellow"></i>
													{{verbose_error}}
													</h4>
												{% endif %}
											{% endif %}
											<div class="space-6"></div>
											<form action="/accounts/auth/" method="POST" accept-charset="utf-8">
												<input type="hidden" name="next" value="{{ next }}" />
												{% csrf_token %}
												<fieldset>
													<label class="block clearfix">
														<span class="block input-icon input-icon-right">
															<input type="text" class="form-control" placeholder="Username" name="username" />
															<i class="ace-icon fa fa-user"></i>
														</span>
													</label>
													<label class="block clearfix">
														<span class="block input-icon input-icon-right">
															<input type="password" class="form-control" placeholder="Password" name="password" />
															<i class="ace-icon fa fa-lock"></i>
														</span>
													</label>
													<div class="space"></div>
													<div class="clearfix">
														<label class="inline">
															<input type="checkbox" class="ace" />
															<span class="lbl"> Remember Me</span>
														</label>
														<button type="submit" class="width-35 pull-right btn btn-sm btn-primary">
														<i class="ace-icon fa fa-key"></i>
														<span class="bigger-110">Login</span>
														</button>
													</div>
													<div class="space-4"></div>
												</fieldset>
											</form>
											</div><!-- /.widget-main -->
											<div class="toolbar clearfix center">
												<h4>&nbsp;&nbsp;También se puede logear con:</h4>
												{% if google_key or facebook_key%}
													{% if google_key %}
														<a  class="user-signup-link" href="{% url 'accounts:social:begin' 'google-oauth2' %}?next={{ next }}">
															<button class="btn btn-lg btn-danger btn-block">
															<i class="ace-icon fa fa-google"></i>
															Google
															</button>
														</a>
													{% endif %}
													{% if facebook_key %}
														<a  class="user-signup-link" href="https://{{request.get_host}}{% url 'accounts:social:begin' backend='facebook' %}?next={{ next }}">
															<button class="btn btn-lg btn-primary btn-block">
															<i class="ace-icon fa fa-facebook"></i>
															Facebook
															</button>
														</a>
													{% endif %}
												{% endif %}
												<a href="#" data-target="#forgot-box" class="forgot-password-link">
													<button class="btn btn-lg btn-warning btn-block">
													<i class="ace-icon fa fa-exclamation"></i>
													Olvidé la Contraseña!!
													</button>
												</a>
												
												
												
												<a href="#" data-target="#signup-box" class="user-signup-link">
													<button class="btn btn-lg btn-success btn-block">
													<i class="ace-icon fa fa-address-book"></i>
													Quiero Registrarme
													</button>
												</a>
												
											</div>
											</div><!-- /.widget-body -->
											</div><!-- /.login-box -->
											<div id="forgot-box" class="forgot-box widget-box no-border">
												<div class="widget-body">
													<div class="widget-main">
														<h4 class="header red lighter bigger">
														<i class="ace-icon fa fa-key"></i>
														Recupero de Contraseña
														</h4>
														<div class="space-6"></div>
														<p>
															Ingrese su correo elecrónico
														</p>
														<form action="{% url 'accounts:password_reset' %}" method="POST" accept-charset="utf-8">
															{% csrf_token %}
															<fieldset>
																{% if form.email.errors %}
																	<span class="red">
																		{{ form.email.errors}}
																	</span>
																{% endif %}
																<span class="block input-icon input-icon-right">
																	<input type="email" name="email" class="form-control" placeholder="Email" />
																	<i class="ace-icon fa fa-envelope"></i>
																</span>
															</label>
															<div class="clearfix">
																<button type="submit" class="pull-right btn btn-sm btn-danger">
																<i class="ace-icon fa fa-lightbulb-o"></i>
																<span class="bigger-110">Enviame la contraseña!</span>
																</button>
															</div>
														</fieldset>
													</form>
													</div><!-- /.widget-main -->
													<div class="toolbar center">
														<a href="#" data-target="#login-box" class="back-to-login-link">
															Volver
															<i class="ace-icon fa fa-arrow-right"></i>
														</a>
													</div>
													</div><!-- /.widget-body -->
													</div><!-- /.forgot-box -->
													<div id="signup-box" class="signup-box widget-box no-border">
														<div class="widget-body">
															<div class="widget-main">
																<h4 class="header green lighter bigger">
																<i class="ace-icon fa fa-users blue"></i>
																Registración de Usuario
																</h4>
																
																<div class="space-6"></div>
																<p> Ingrese los siguientes datos: </p>
																<form action="/accounts/registration/" method="POST" accept-charset="utf-8">
																	{% csrf_token %}
																	<fieldset>
																		<label class="block clearfix">
																			{{form.nombres.errors}}
																			<span class="block input-icon input-icon-right">
																				<input type="text" class="form-control" placeholder="Nombres" name="nombres" value='{{form.nombres.value|default:""}}'/>
																				<i class="ace-icon fa fa-user"></i>
																			</span>
																		</label>
																		<label class="block clearfix">
																			{{form.apellidos.errors}}
																			<span class="block input-icon input-icon-right">
																				<input type="text" class="form-control" placeholder="Apellidos" name="apellidos" value='{{form.apellidos.value|default:""}}'/>
																				<i class="ace-icon fa fa-user"></i>
																			</span>
																		</label>
																		<label class="block clearfix">
																			{{form.email.errors}}
																			<span class="block input-icon input-icon-right">
																				<input type="email" class="form-control" placeholder="Email" name="email" value='{{form.email.value|default:""}}'/>
																				<i class="ace-icon fa fa-envelope"></i>
																			</span>
																		</label>
																		<label class="block clearfix">
																			{{form.username.errors}}
																			<span class="block input-icon input-icon-right">
																				<input type="text" class="form-control" placeholder="Username" name="username" value='{{form.username.value|default:""}}' />
																				<i class="ace-icon fa fa-user"></i>
																			</span>
																		</label>
																		<label class="block clearfix">
																			{{form.password1.errors}}
																			<span class="block input-icon input-icon-right">
																				<input type="password" class="form-control" placeholder="Password"  name="password1" value='{{form.password1.value|default:""}}'/>
																				<i class="ace-icon fa fa-lock"></i>
																			</span>
																		</label>
																		<label class="block clearfix">
																			{{form.password2.errors}}
																			<span class="block input-icon input-icon-right">
																				<input type="password" class="form-control" placeholder="Repeat password"  name="password2" value='{{form.password2.value|default:""}}'/>
																				<i class="ace-icon fa fa-retweet"></i>
																			</span>
																		</label>
																		{% if form.secret %}
																			<p> Ingrese la frase secreta </p>
																			<label class="block clearfix">
																				{{form.secret.errors}}
																				<span class="block input-icon input-icon-right">
																					<input type="password" class="form-control" placeholder="Frase Secreta"  name="secret" value='{{form.secret.value|default:""}}'/>
																					<i class="ace-icon fa fa-question-circle"></i>
																				</span>
																			</label>
																		{% endif %}
																		{{ form.captcha.errors }}
																		{{ form.captcha }}
																		
																		<div class="space-24"></div>
																		<div class="clearfix">
																			<button type="reset" class="width-30 pull-left btn btn-sm">
																			<i class="ace-icon fa fa-refresh"></i>
																			<span class="bigger-110">Limpiar</span>
																			</button>
																			<button type="button" class="width-65 pull-right btn btn-sm btn-success" onclick="this.form.submit()">
																			<span class="bigger-110">Registrar</span>
																			<i class="ace-icon fa fa-arrow-right icon-on-right"></i>
																			</button>
																		</div>
																	</fieldset>
																</form>
															</div>
															<div class="toolbar center">
																<a href="#" data-target="#login-box" class="back-to-login-link">
																	<i class="ace-icon fa fa-arrow-left"></i>
																	Volver
																</a>
															</div>
															</div><!-- /.widget-body -->
															</div><!-- /.signup-box -->
															</div><!-- /.position-relative -->
															<div class="navbar-fixed-top align-right">
																<br />
																&nbsp;
																<a id="btn-login-dark" href="#">Dark</a>
																&nbsp;
																<span class="blue">/</span>
																&nbsp;
																<a id="btn-login-blur" href="#">Blur</a>
																&nbsp;
																<span class="blue">/</span>
																&nbsp;
																<a id="btn-login-light" href="#">Light</a>
																&nbsp; &nbsp; &nbsp;
															</div>
														</div>
														</div><!-- /.col -->
														</div><!-- /.row -->
														</div><!-- /.main-content -->
														</div><!-- /.main-container -->
														{% include "generic_views/basic_scripts.html" %}
													</body>
													{% block javascript %}
														<!-- inline scripts related to this page -->
														<script type="text/javascript">
															jQuery(function($) {
															$(document).on('click', '.toolbar a[data-target]', function(e) {
																e.preventDefault();
																var target = $(this).data('target');
																$('.widget-box.visible').removeClass('visible');//hide others
																$(target).addClass('visible');//show target
															});
															});
															{% if active_form %}
																	$(function() {
																		var target = ".{{active_form}}";
																		$('.widget-box.visible').removeClass('visible');//hide others
																		$(target).addClass('visible');//show target
																	});
															{% endif %}
															
															
															//you don't need this, just used for changing background
															jQuery(function($) {
															$('#btn-login-dark').on('click', function(e) {
																$('body').attr('class', 'login-layout');
																$('#id-text2').attr('class', 'white');
																$('#id-company-text').attr('class', 'blue');
																
																e.preventDefault();
															});
															$('#btn-login-light').on('click', function(e) {
																$('body').attr('class', 'login-layout light-login');
																$('#id-text2').attr('class', 'grey');
																$('#id-company-text').attr('class', 'blue');
																
																e.preventDefault();
															});
															$('#btn-login-blur').on('click', function(e) {
																$('body').attr('class', 'login-layout blur-login');
																$('#id-text2').attr('class', 'white');
																$('#id-company-text').attr('class', 'light-blue');
																
																e.preventDefault();
															});
															
															});
														</script>
													{% endblock %}
												{% endblock %}

templates/accounts/login_logo.html
{% load static %}
<!--
<img src="{% static 'accounts/logo.png' %}" /> 
-->

templates/accounts/password.html
{% extends "generic_views/base.html" %}
{%load static %}
{% block body %}
<body class="login-layout light-login">
		<div class="main-container">
			<div class="main-content">
				<div class="row">
					<div class="col-sm-10 col-sm-offset-1">
						<div class="login-container">
							<div class="center">
								{%include "accounts/login_logo.html" %}
							</div>

							<div class="space-6"></div>

							<div class="position-relative">
								<div id="login-box" class="login-box visible widget-box no-border">
									<div class="widget-body">
										<div class="widget-main">
											<h4 class="header blue lighter bigger">
												<i class="ace-icon fa fa-coffee green"></i>
												Cambio de Contraseña
											</h4>
											{% if errors %}
											<h4 class="header red">
												{% for e in errors %}
												<i class="ace-icon fa fa-warning yellow"></i>
												{{e}}
												{%endfor%}
											</h4>
											{% endif %}
											<div class="space-6"></div>
											<form action="{% url 'accounts:change_password' %}" method="POST" accept-charset="utf-8">
												<input type="hidden" name="next" value="{{ next }}" />
												{% csrf_token %}
												<fieldset>
													<label class="block clearfix">
														<span class="block input-icon input-icon-right">
															<input type="password" class="form-control" placeholder="Password" name="password" />
															<i class="ace-icon fa fa-lock"></i>
														</span>
													</label>

													<label class="block clearfix">
														<span class="block input-icon input-icon-right">
															<input type="password" class="form-control" placeholder="Re-Password" name="repassword" />
															<i class="ace-icon fa fa-lock"></i>
														</span>
													</label>

													<div class="space"></div>

													<div class="clearfix">

														<button type="submit" class="btn btn-sm btn-primary">
															<i class="ace-icon fa fa-key"></i>
															<span class="bigger-110">Cambiar Contraseña</span>
														</button>
													</div>

													<div class="space-4"></div>
												</fieldset>
											</form>

										</div>
									</div>
								</div>
							</div><!-- /.position-relative -->
						</div>
					</div><!-- /.col -->
				</div><!-- /.row -->
			</div><!-- /.main-content -->
		</div><!-- /.main-container -->

{% include "generic_views/basic_scripts.html" %}

	</body>

{% block javascript %}
		<!-- inline scripts related to this page -->
		<script type="text/javascript">
			
		</script>
{% endblock %}


{% endblock %}

templates/accounts/password_reset_complete.html
{% extends "generic_views/base.html" %}
{%load static %}
{% block body %}
<body class="login-layout light-login">
		<div class="main-container">
			<div class="main-content">
				<div class="row">
					<div class="col-sm-10 col-sm-offset-1">
						<div class="login-container">
							<div class="center">
								{%include "accounts/login_logo.html" %}
							</div>

							<div class="space-6"></div>

							<div class="position-relative">
								<div id="login-box" class="login-box visible widget-box no-border">
									<div class="widget-body">
										<div class="widget-main">
												<h4 class="header">
													Su contraseña a sido restablecida
												</h4>
												<a href="{% url 'accounts:login' %}"> Ingresar </a>
										</div>
									</div>
								</div>
							</div><!-- /.position-relative -->
						</div>
					</div><!-- /.col -->
				</div><!-- /.row -->
			</div><!-- /.main-content -->
		</div><!-- /.main-container -->

{% include "generic_views/basic_scripts.html" %}

	</body>

{% block javascript %}
		<!-- inline scripts related to this page -->
		<script type="text/javascript">
			
		</script>
{% endblock %}


{% endblock %}

templates/accounts/password_reset_done.html
{% extends "generic_views/base.html" %}
{%load static %}
{% block body %}
<body class="login-layout light-login">
		<div class="main-container">
			<div class="main-content">
				<div class="row">
					<div class="col-sm-10 col-sm-offset-1">
						<div class="login-container">
							<div class="center">
								{%include "accounts/login_logo.html" %}
							</div>

							<div class="space-6"></div>

							<div class="position-relative">
								<div id="login-box" class="login-box visible widget-box no-border">
									<div class="widget-body">
										<div class="widget-main">
												<h4 class="header">
													Hemos enviado una solicitud de cambio de contraseña a tu correo electrónico, revisálo, especialmente la seccion spam.
												</h4>
										</div>
									</div>
								</div>
							</div><!-- /.position-relative -->
						</div>
					</div><!-- /.col -->
				</div><!-- /.row -->
			</div><!-- /.main-content -->
		</div><!-- /.main-container -->

{% include "generic_views/basic_scripts.html" %}

	</body>

{% block javascript %}
		<!-- inline scripts related to this page -->
		<script type="text/javascript">
			
		</script>
{% endblock %}


{% endblock %}

templates/accounts/password_reset_form.html
{% extends "generic_views/base.html" %}
{%load static %}
{% block body %}
<body class="login-layout light-login">
		<div class="main-container">
			<div class="main-content">
				<div class="row">
					<div class="col-sm-10 col-sm-offset-1">
						<div class="login-container">
							<div class="center">
								{%include "accounts/login_logo.html" %}
							</div>

							<div class="space-6"></div>

							<div class="position-relative">
								<div id="login-box" class="login-box visible widget-box no-border">
									<div class="widget-body">
										<div class="widget-main">
											<h4 class="header blue lighter bigger">
												<i class="ace-icon fa fa-coffee green"></i>
												Cambio de Contraseña
											</h4>
											{% if validlink %}
											<h4 class="header red">
												{{ form.new_password1.errors }}
												{{ form.new_password2.errors }}
											</h4>
											
											<div class="space-6"></div>
											<form action="" method="POST" accept-charset="utf-8">
												<input type="hidden" name="next" value="{{ next }}" />
												{% csrf_token %}
												<fieldset>
													<label class="block clearfix">
														<span class="block input-icon input-icon-right">
															<input type="password" class="form-control" placeholder="Password" name="new_password1" />
															<i class="ace-icon fa fa-lock"></i>
														</span>
													</label>

													<label class="block clearfix">
														<span class="block input-icon input-icon-right">
															<input type="password" class="form-control" placeholder="Re-Password" name="new_password2" />
															<i class="ace-icon fa fa-lock"></i>
														</span>
													</label>

													<div class="space"></div>

													<div class="clearfix">

														<button type="submit" class="btn btn-sm btn-primary">
															<i class="ace-icon fa fa-key"></i>
															<span class="bigger-110">Cambiar Contraseña</span>
														</button>
													</div>

													<div class="space-4"></div>
												</fieldset>
											</form>
											{% else %}
												El link especificado no corresponde, está vencido o ya fue usado.
												<br />
												<a href="/accounts/password/reset/">Volvewr a recuperar contraseña</a>
											{% endif %}
										</div>
									</div>
								</div>
							</div><!-- /.position-relative -->
						</div>
					</div><!-- /.col -->
				</div><!-- /.row -->
			</div><!-- /.main-content -->
		</div><!-- /.main-container -->

{% include "generic_views/basic_scripts.html" %}

	</body>

{% block javascript %}
		<!-- inline scripts related to this page -->
		<script type="text/javascript">
			
		</script>
{% endblock %}


{% endblock %}

templates/accounts/pasword_reset.html
{% extends "generic_views/base.html" %}
{%load static %}
{% block body %}
<body class="login-layout light-login">
		<div class="main-container">
			<div class="main-content">
				<div class="row">
					<div class="col-sm-10 col-sm-offset-1">
						<div class="login-container">
							<div class="center">
								{%include "accounts/login_logo.html" %}
							</div>

							<div class="space-6"></div>

							<div class="position-relative">
								<div id="login-box" class="login-box visible widget-box no-border">
									<div class="widget-body">
										<div class="widget-main">
											{% if validlink %}
											<h4 class="header blue lighter bigger">
												<i class="ace-icon fa fa-coffee green"></i>
												Recupero de Contraseña
											</h4>
											<h4 class="header red">
												{{ form.new_password1.errors }}
												{{ form.new_password2.errors }}
											</h4>
											<div class="space-6"></div>
											<form action="{% url 'accounts:change:password' %}" method="POST" accept-charset="utf-8">
												<input type="hidden" name="next" value="{{ next }}" />
												<input type="hidden" name="token" value="{{ token }}" />
												{% csrf_token %}
												<fieldset>
													<label class="block clearfix">
														<span class="block input-icon input-icon-right">
															<input type="password" class="form-control" placeholder="Password" name="id_new_password1" />
															<i class="ace-icon fa fa-lock"></i>
														</span>
													</label>

													<label class="block clearfix">
														<span class="block input-icon input-icon-right">
															<input type="password" class="form-control" placeholder="Re-Password" name="id_new_password2" />
															<i class="ace-icon fa fa-lock"></i>
														</span>
													</label>

													<div class="space"></div>

													<div class="clearfix">

														<button type="submit" class="btn btn-sm btn-primary">
															<i class="ace-icon fa fa-key"></i>
															<span class="bigger-110">Cambiar Contraseña</span>
														</button>
													</div>

													<div class="space-4"></div>
												</fieldset>
											</form>
											{% else %}
												<h4 class="header red">
													El enlace provisto es inválido, posiblemente esta vencido
												</h4>
											{% endif %}
										</div>
									</div>
								</div>
							</div><!-- /.position-relative -->
						</div>
					</div><!-- /.col -->
				</div><!-- /.row -->
			</div><!-- /.main-content -->
		</div><!-- /.main-container -->

{% include "generic_views/basic_scripts.html" %}

	</body>

{% block javascript %}
		<!-- inline scripts related to this page -->
		<script type="text/javascript">
			
		</script>
{% endblock %}


{% endblock %}

templates/accounts/profile.html
{% extends "generic_views/base.html" %}
{% load static %}
{% block page-content %}
	<div id="user-profile-2" class="user-profile">
		<div class="tabbable">
			<ul class="nav nav-tabs padding-18">
				<li class="active">
					<a data-toggle="tab" href="#home">
						<i class="green ace-icon fa fa-user bigger-120"></i>
						Profile
					</a>
				</li>
				<li>
					<a data-toggle="tab" href="#friends">
						<i class="blue ace-icon fa fa-users bigger-120"></i>
						Amigos
					</a>
				</li>
			</ul>

			<div class="tab-content no-border padding-24">
				<div id="home" class="tab-pane in active">
					{% include "accounts/profile_user.html" %}
				</div><!-- /#home -->

				<div id="friends" class="tab-pane">
					<!-- #section:pages/profile.friends -->
					{% include "accounts/profile_friends.html"%}
					<!-- /section:pages/profile.friends -->
					<div class="hr hr10 hr-double"></div>
				</div><!-- /#friends -->
			</div>
		</div>
	</div>
</div>


{% endblock %}

{% block javascript %}
<script type="text/javascript" src="{% static 'ace_admin/assets/js/x-editable/bootstrap-editable.js' %}"></script>
<script type="text/javascript" src="{% static 'ace_admin/assets/js/x-editable/ace-editable.js' %}"></script>
<script type="text/javascript" src="{% static 'accounts/js/profile_edit.js' %}"></script>

{% if usuario == user %}
<script type="text/javascript">
	$(document).ready(profile_edit_inicialize);
</script>
{% endif %}
{% endblock %}

templates/accounts/profile_friends.html
{% load static %}					
					<div class="profile-users clearfix">
					{% for friend in friends %}
						<div class="itemdiv memberdiv">
							<div class="inline pos-rel">
								<div class="user">
									<a href="{% url 'accounts:profile' %}?username={{friend.username|urlencode}}"><img {% if friend.profile.is_online %}style="border:3px solid #8AC16C"{%endif%} src="{% if friend.profile.get_profile_avatar %}{{friend.profile.get_profile_avatar.url}}
									{%else%} {% static 'accounts/noavatar.png' %} {%endif%}" title="última actividad: {{friend.profile.verbose_last_activity}}" /></a>
								</div>

								<div class="body">
									<div class="name">
											{% if friend.profile %}
											{{friend.profile.full_name}}
											{% else %}
											{{friend.username}}
											{% endif %}
									</div>
								</div>
							</div>
						</div>
						{%endfor%}
					</div>

templates/accounts/profile_user.html
{% load static%}					
					<div class="row">
						<div class="col-xs-12 col-sm-3 center">

							<span class="profile-picture">
								<img class="editable img-responsive editable-click editable-empty" alt="Avatar" id="avatar" src="{% if usuario.profile.get_profile_avatar.url %}{{usuario.profile.get_profile_avatar.url}}{% else %}{% static 'accounts/noavatar.png' %}{% endif %}"/>
							</span>

							<div class="space space-4"></div>

						</div><!-- /.col -->

						<div class="col-xs-12 col-sm-9">
							<h4 class="blue">
								<span id="first_name" class="middle">{{usuario.first_name}}</span>
								<span id="last_name" class="middle"> {{usuario.last_name}}</span>
								{% if usuario.profile.is_online %}
								<span class="label label-success arrowed-in-right">
									<i class="ace-icon fa fa-circle smaller-80 align-middle"></i>
									online
								</span>
								{% else%}
									<span class="label arrowed-in-right">
									<i class="ace-icon fa fa-circle smaller-80 align-middle"></i>
									offline
								</span>
								{% endif %}
							</h4>

							<div class="profile-user-info">
								<div class="profile-info-row">
									<div class="profile-info-name"> Usuario </div>

									<div class="profile-info-value">
										<span id="username">{{usuario.username}}</span>
									</div>
								</div>
								<div class="profile-info-row">
									<div class="profile-info-name"> E-Mail </div>

									<div class="profile-info-value">
										<span id="email">{{usuario.email}}</span>
									</div>
								</div>
								{% if usuario == user %}
								<div class="profile-info-row">
									<div class="profile-info-name"> Contraseña </div>

									<div class="profile-info-value">
										<a href="{% url 'accounts:change_password' %}"><span id="password">********</span></a>
									</div>
								</div>
								{% endif %}
								
								<div class="profile-info-row">
									<div class="profile-info-name"> Última Actividad </div>

									<div class="profile-info-value">
										<span>{{usuario.profile.verbose_last_activity}}</span>
									</div>
								</div>
							</div>
						</div><!-- /.col -->
					</div><!-- /.row -->

templates/accounts/registration.html
{{form}}

templates/accounts/user_avatar.html
{% load static %}
<div class="itemdiv memberdiv">
	<div class="user">
		<img {% if usuario.profile.is_online %}style="border:3px solid #8AC16C"{%endif%} alt="avatar" src="{% if usuario.profile.get_profile_avatar.url %}{{usuario.profile.get_profile_avatar.url}}{% else %}{% static 'accounts/noavatar.png' %}{% endif %}" />
	</div>

	<div class="body">
		<div class="name">
			<a href="#">{{usuario.profile.full_name}}</a>
		</div>

		<div class="time">
			<i class="ace-icon fa {{icon|default:'fa-clock-o'}} orange"></i>
			<span class="{{color|default:'green'}}">{{label}}</span>
		</div>
	</div>
</div>